<?php

declare(strict_types=1);

return array(
    'tree_traversal_with_scope' => array(
        array(
            'name' => null,
            'lft' => 10,
            'rgt' => 0,
            'parent_id' => null,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 11,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 12,
            'rgt' => 0,
            'parent_id' => 2,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 13,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 14,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 15,
            'rgt' => 0,
            'parent_id' => 5,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 16,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 17,
            'rgt' => 0,
            'parent_id' => 2,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 18,
            'rgt' => 0,
            'parent_id' => 2,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 19,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 20,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 21,
            'rgt' => 0,
            'parent_id' => 5,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 22,
            'rgt' => 0,
            'parent_id' => 5,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 23,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 24,
            'rgt' => 0,
            'parent_id' => 1,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 25,
            'rgt' => 0,
            'parent_id' => 4,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 26,
            'rgt' => 0,
            'parent_id' => 4,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'name' => null,
            'lft' => 1,
            'rgt' => 6,
            'parent_id' => null,
            'level' => 0,
            'scope' => 2,
        ),
        array(
            'name' => null,
            'lft' => 2,
            'rgt' => 5,
            'parent_id' => 18,
            'level' => 1,
            'scope' => 2,
        ),
        array(
            'name' => null,
            'lft' => 3,
            'rgt' => 4,
            'parent_id' => 19,
            'level' => 2,
            'scope' => 2,
        ),
    ),
);
