<?php

declare(strict_types=1);

return array(
    'tree_traversal_with_scope' => array(
        array(
            'tree_traversal_id' => 1,
            'name' => null,
            'lft' => 1,
            'rgt' => 34,
            'parent_id' => null,
            'level' => 0,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 2,
            'name' => null,
            'lft' => 2,
            'rgt' => 9,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 3,
            'name' => null,
            'lft' => 3,
            'rgt' => 4,
            'parent_id' => 2,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 4,
            'name' => null,
            'lft' => 10,
            'rgt' => 15,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 5,
            'name' => null,
            'lft' => 16,
            'rgt' => 23,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 6,
            'name' => null,
            'lft' => 17,
            'rgt' => 18,
            'parent_id' => 5,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 7,
            'name' => null,
            'lft' => 24,
            'rgt' => 25,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 8,
            'name' => null,
            'lft' => 5,
            'rgt' => 6,
            'parent_id' => 2,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 9,
            'name' => null,
            'lft' => 7,
            'rgt' => 8,
            'parent_id' => 2,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 10,
            'name' => null,
            'lft' => 26,
            'rgt' => 27,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 11,
            'name' => null,
            'lft' => 28,
            'rgt' => 29,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 12,
            'name' => null,
            'lft' => 19,
            'rgt' => 20,
            'parent_id' => 5,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 13,
            'name' => null,
            'lft' => 21,
            'rgt' => 22,
            'parent_id' => 5,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 14,
            'name' => null,
            'lft' => 30,
            'rgt' => 31,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 15,
            'name' => null,
            'lft' => 32,
            'rgt' => 33,
            'parent_id' => 1,
            'level' => 1,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 16,
            'name' => null,
            'lft' => 11,
            'rgt' => 12,
            'parent_id' => 4,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 17,
            'name' => null,
            'lft' => 13,
            'rgt' => 14,
            'parent_id' => 4,
            'level' => 2,
            'scope' => 1,
        ),
        array(
            'tree_traversal_id' => 18,
            'name' => null,
            'lft' => 1,
            'rgt' => 6,
            'parent_id' => null,
            'level' => 0,
            'scope' => 2,
        ),
        array(
            'tree_traversal_id' => 19,
            'name' => null,
            'lft' => 2,
            'rgt' => 5,
            'parent_id' => 18,
            'level' => 1,
            'scope' => 2,
        ),
        array(
            'tree_traversal_id' => 20,
            'name' => null,
            'lft' => 3,
            'rgt' => 4,
            'parent_id' => 19,
            'level' => 2,
            'scope' => 2,
        ),
    ),
);
