<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StefanoTree\Adapter\AdapterInterface' => __DIR__ . '/src/StefanoTree/Adapter/AdapterInterface.php',
    'StefanoTree\Adapter\DbTraversal'      => __DIR__ . '/src/StefanoTree/Adapter/DbTraversal.php',
    'StefanoTree\NodeInfo'                 => __DIR__ . '/src/StefanoTree/NodeInfo.php',
);
