<?php

declare(strict_types=1);

return array(
    'tree_traversal' => array(
        array(
            'tree_traversal_id' => 1,
            'name' => null,
            'lft' => 1,
            'rgt' => 50,
            'parent_id' => null,
            'level' => 0,
        ),
        array(
            'tree_traversal_id' => 2,
            'name' => null,
            'lft' => 2,
            'rgt' => 11,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 3,
            'name' => null,
            'lft' => 12,
            'rgt' => 45,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 4,
            'name' => null,
            'lft' => 46,
            'rgt' => 49,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 5,
            'name' => null,
            'lft' => 3,
            'rgt' => 10,
            'parent_id' => 2,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 6,
            'name' => null,
            'lft' => 37,
            'rgt' => 42,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 7,
            'name' => null,
            'lft' => 43,
            'rgt' => 44,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 8,
            'name' => null,
            'lft' => 47,
            'rgt' => 48,
            'parent_id' => 4,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 9,
            'name' => null,
            'lft' => 15,
            'rgt' => 24,
            'parent_id' => 21,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 10,
            'name' => null,
            'lft' => 4,
            'rgt' => 7,
            'parent_id' => 5,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 11,
            'name' => null,
            'lft' => 8,
            'rgt' => 9,
            'parent_id' => 5,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 12,
            'name' => null,
            'lft' => 38,
            'rgt' => 39,
            'parent_id' => 6,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 13,
            'name' => null,
            'lft' => 40,
            'rgt' => 41,
            'parent_id' => 6,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 14,
            'name' => null,
            'lft' => 16,
            'rgt' => 21,
            'parent_id' => 9,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 15,
            'name' => null,
            'lft' => 22,
            'rgt' => 23,
            'parent_id' => 9,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 16,
            'name' => null,
            'lft' => 33,
            'rgt' => 36,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 17,
            'name' => null,
            'lft' => 5,
            'rgt' => 6,
            'parent_id' => 10,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 18,
            'name' => null,
            'lft' => 13,
            'rgt' => 32,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 19,
            'name' => null,
            'lft' => 17,
            'rgt' => 20,
            'parent_id' => 14,
            'level' => 6,
        ),
        array(
            'tree_traversal_id' => 20,
            'name' => null,
            'lft' => 34,
            'rgt' => 35,
            'parent_id' => 16,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 21,
            'name' => null,
            'lft' => 14,
            'rgt' => 29,
            'parent_id' => 18,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 22,
            'name' => null,
            'lft' => 30,
            'rgt' => 31,
            'parent_id' => 18,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 23,
            'name' => null,
            'lft' => 18,
            'rgt' => 19,
            'parent_id' => 19,
            'level' => 7,
        ),
        array(
            'tree_traversal_id' => 24,
            'name' => null,
            'lft' => 25,
            'rgt' => 26,
            'parent_id' => 21,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 25,
            'name' => null,
            'lft' => 27,
            'rgt' => 28,
            'parent_id' => 21,
            'level' => 4,
        ),
    ),
);
