<?php

declare(strict_types=1);

return array(
    'tree_traversal' => array(
        array(
            'tree_traversal_id' => 1,
            'name' => null,
            'lft' => 1,
            'rgt' => 50,
            'parent_id' => null,
            'level' => 0,
        ),
        array(
            'tree_traversal_id' => 2,
            'name' => null,
            'lft' => 2,
            'rgt' => 15,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 3,
            'name' => null,
            'lft' => 516,
            'rgt' => 35,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 4,
            'name' => null,
            'lft' => 536,
            'rgt' => 49,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 5,
            'name' => null,
            'lft' => 3,
            'rgt' => 14,
            'parent_id' => 2,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 6,
            'name' => null,
            'lft' => 517,
            'rgt' => 32,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 7,
            'name' => null,
            'lft' => 533,
            'rgt' => 34,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 8,
            'name' => null,
            'lft' => 537,
            'rgt' => 38,
            'parent_id' => 4,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 9,
            'name' => null,
            'lft' => 539,
            'rgt' => 48,
            'parent_id' => 4,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 10,
            'name' => null,
            'lft' => 4,
            'rgt' => 11,
            'parent_id' => 5,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 11,
            'name' => null,
            'lft' => 12,
            'rgt' => 13,
            'parent_id' => 5,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 12,
            'name' => null,
            'lft' => 518,
            'rgt' => 29,
            'parent_id' => 6,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 13,
            'name' => null,
            'lft' => 530,
            'rgt' => 31,
            'parent_id' => 6,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 14,
            'name' => null,
            'lft' => 540,
            'rgt' => 45,
            'parent_id' => 9,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 15,
            'name' => null,
            'lft' => 546,
            'rgt' => 47,
            'parent_id' => 9,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 16,
            'name' => null,
            'lft' => 5,
            'rgt' => 8,
            'parent_id' => 10,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 17,
            'name' => null,
            'lft' => 9,
            'rgt' => 10,
            'parent_id' => 10,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 18,
            'name' => null,
            'lft' => 519,
            'rgt' => 28,
            'parent_id' => 12,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 19,
            'name' => null,
            'lft' => 541,
            'rgt' => 44,
            'parent_id' => 14,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 20,
            'name' => null,
            'lft' => 6,
            'rgt' => 7,
            'parent_id' => 16,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 21,
            'name' => null,
            'lft' => 520,
            'rgt' => 25,
            'parent_id' => 18,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 22,
            'name' => null,
            'lft' => 526,
            'rgt' => 27,
            'parent_id' => 18,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 23,
            'name' => null,
            'lft' => 542,
            'rgt' => 43,
            'parent_id' => 19,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 24,
            'name' => null,
            'lft' => 521,
            'rgt' => 22,
            'parent_id' => 21,
            'level' => 6,
        ),
        array(
            'tree_traversal_id' => 25,
            'name' => null,
            'lft' => 523,
            'rgt' => 24,
            'parent_id' => 21,
            'level' => 6,
        ),
    ),
);
