<?php

declare(strict_types=1);

return array(
    'tree_traversal' => array(
        array(
            'tree_traversal_id' => 1,
            'name' => null,
            'lft' => 1,
            'rgt' => 550,
            'parent_id' => null,
            'level' => 0,
        ),
        array(
            'tree_traversal_id' => 2,
            'name' => null,
            'lft' => 2,
            'rgt' => 15,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 3,
            'name' => null,
            'lft' => 16,
            'rgt' => 535,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 4,
            'name' => null,
            'lft' => 36,
            'rgt' => 549,
            'parent_id' => 1,
            'level' => 1,
        ),
        array(
            'tree_traversal_id' => 5,
            'name' => null,
            'lft' => 3,
            'rgt' => 14,
            'parent_id' => 2,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 6,
            'name' => null,
            'lft' => 17,
            'rgt' => 532,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 7,
            'name' => null,
            'lft' => 33,
            'rgt' => 534,
            'parent_id' => 3,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 8,
            'name' => null,
            'lft' => 37,
            'rgt' => 538,
            'parent_id' => 4,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 9,
            'name' => null,
            'lft' => 39,
            'rgt' => 548,
            'parent_id' => 4,
            'level' => 2,
        ),
        array(
            'tree_traversal_id' => 10,
            'name' => null,
            'lft' => 4,
            'rgt' => 11,
            'parent_id' => 5,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 11,
            'name' => null,
            'lft' => 12,
            'rgt' => 13,
            'parent_id' => 5,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 12,
            'name' => null,
            'lft' => 18,
            'rgt' => 529,
            'parent_id' => 6,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 13,
            'name' => null,
            'lft' => 30,
            'rgt' => 531,
            'parent_id' => 6,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 14,
            'name' => null,
            'lft' => 40,
            'rgt' => 545,
            'parent_id' => 9,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 15,
            'name' => null,
            'lft' => 46,
            'rgt' => 547,
            'parent_id' => 9,
            'level' => 3,
        ),
        array(
            'tree_traversal_id' => 16,
            'name' => null,
            'lft' => 5,
            'rgt' => 8,
            'parent_id' => 10,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 17,
            'name' => null,
            'lft' => 9,
            'rgt' => 10,
            'parent_id' => 10,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 18,
            'name' => null,
            'lft' => 19,
            'rgt' => 528,
            'parent_id' => 12,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 19,
            'name' => null,
            'lft' => 41,
            'rgt' => 544,
            'parent_id' => 14,
            'level' => 4,
        ),
        array(
            'tree_traversal_id' => 20,
            'name' => null,
            'lft' => 6,
            'rgt' => 7,
            'parent_id' => 16,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 21,
            'name' => null,
            'lft' => 20,
            'rgt' => 525,
            'parent_id' => 18,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 22,
            'name' => null,
            'lft' => 26,
            'rgt' => 527,
            'parent_id' => 18,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 23,
            'name' => null,
            'lft' => 42,
            'rgt' => 543,
            'parent_id' => 19,
            'level' => 5,
        ),
        array(
            'tree_traversal_id' => 24,
            'name' => null,
            'lft' => 21,
            'rgt' => 522,
            'parent_id' => 21,
            'level' => 6,
        ),
        array(
            'tree_traversal_id' => 25,
            'name' => null,
            'lft' => 23,
            'rgt' => 524,
            'parent_id' => 21,
            'level' => 6,
        ),
    ),
);
